apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    myapp: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    myapp: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: demo
  template:
    metadata:
      labels:
        myapp: demo
    spec:
      containers:
      - name: web
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
