apiVersion: v1
kind: Pod
metadata:
  name: pod-jai
  labels:
    myapp: pod-jai
spec:
  containers:
    - name: web
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: jai-nginx-service
spec:
  type: ClusterIP
  selector:
    myapp: pod-jai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
