apiVersion: apps/v1
kind: Deployment
metadata:
  name: myname
  labels:
    myapp: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      myapp: myname
  template:
    metadata:
      labels:
        myapp: myname
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
