apiVersion: v1
kind: Service
metadata:
  name: yourename-service
spec:
  type: ClusterIP
  selector:
    myapp: yourename
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourename
  labels:
    myapp: yourename
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: yourename
  template:
    metadata:
      labels:
        myapp: yourename
    spec:
      containers:
      - name: web
        image: stenote/nginx-hostname
        ports:
        - containerPort: 80
