apiVersion: apps/v1
kind: Deployment
metadata:
  name: jai-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jai
  template:
    metadata:
      labels:
        app: jai
    spec:
      containers:
      - name: web
        image: nginx:1.20
        ports:
        - containerPort: 80
