apiVersion: apps/v1
kind: Deployment
metadata:
  name: jai-deployment
  labels:
    app: nginx
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  replicas: 2
  selector:
    matchLabels:
      app: jai
  template:
    metadata:
      labels:
        app: jai
    spec:
      containers:
      - name: web
        image: nginx:1.20
        volumeMounts:
        - mountPath: "/var/log/nginx"
          name: task-pv-storage
        ports:
        - containerPort: 80
