apiVersion: v1
kind: Secret
metadata:
  name: secret-myname
data:
  platform: a3ViZXJuZXRlcwo=

---
apiVersion: v1
kind: Pod 
metadata:
  name: testpod-myname 
spec:
  containers:
  - image: nginx
    name: web
    env: 
    - name: PLATFORM
      valueFrom:
        secretKeyRef:
          name: secret-myname
          key: platform  
