apiVersion: v1
kind: Secret
metadata:
  name: yourname
data:
  application-owner: "yoursecrect"

---
apiVersion: v1
kind: Pod 
metadata:
  name: yourname 
spec:
  containers:
  - image: nginx
    name: web
    env:
    - name: OWNER
      valueFrom:
        secretKeyRef:
          name: yourname
          key: application-owner
