apiVersion: v1
kind: ConfigMap
metadata:
  name: config-myname
data:
  application-owner: "myname"

---
apiVersion: v1
kind: Pod 
metadata:
  name: myname 
spec:
  containers:
  - image: nginx
    name: web
    env: 
    - name: OWNER
      valueFrom:
        configMapKeyRef:
          name: config-myname
          key: application-owner  
