apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-myname
spec:
  storageClassName: manual
  volumeName: pv-myname
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
