apiVersion: v1
kind: ReplicationController
metadata:
  name: myname
spec:
  replicas: 3
  selector:
    app: myname
  template:
    metadata:
      name: nginx
      labels:
        app: myname
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
