apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myname
  labels: 
    app: myapp 
spec:
  template:
    metadata:
      name: pod
      labels: 
        myapp: myname
    spec:
      containers:
      - name: web
        image: nginx 
  replicas: 2
  selector: 
    matchLabels:
      myapp: myname 
