apiVersion: v1
kind: Service
metadata:
  name: mysql-myname
spec:
  type: NodePort
  ports:
  - port: 3306
  selector:
    app: mysql-myname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-myname
spec:
  selector:
    matchLabels:
      app: mysql-myname
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-myname
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: bSqdYYqsqU5VPj2g
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-myname
