apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-db
data:
  password: WEZNNDZUS3BuV0ZYOEVKYQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
spec:
  storageClassName: manual
  volumeName: pv-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - image: postgres:latest
        name: database
        env: 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-db
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: pvc-db
          
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres-db 
