apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-jai-db
spec:
  podSelector:
    matchLabels:
      run: jai-db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: jai-backend
