apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-jai-backend
spec:
  podSelector:
    matchLabels:
      run=jai-backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run=jai-frontend
