apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jaibw/angular-app:12
        ports:
        - containerPort: 80
        env:
        - name: SPRING_BOOT_URL
          value: "http://10.104.32.71:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: frontend
