apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DBNAME: "demo"
  DBUSER: "root"
  DBPASS: "bSqdYYqsqU5VPj2g"
  DBHOST: "mysql"
  DBPORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: ovs
        image: jaibw/spring-boot-data:2
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    app: myapp
