apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DBNAME: "postgres"
  DBUSER: "postgres"
  DBPASS: "XFM46TKpnWFX8EJa"
  DBHOST: "postgres-jai"
  DBPORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: ovs
        image: jaibw/spring-boot-data:1 
        ports:
        - containerPort: 8080 
        envFrom:
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - targetPort: 8093 
    port: 8093 
  selector:
    app: myapp
