apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod001
  name: pod001
spec:
  containers:
  - image: curlimages/curl:latest
    name: pod001
    resources: {}
    command:
    - sh
    - -c
    - sleep 3d
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: user001
status: {}
