apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: project001-role-user001
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project001role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: project001user
- kind: ServiceAccount
  name: user001
  namespace: project001
