apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnostic-app
  template:
    metadata:
      name: diagnostic
      labels:
        app: diagnostic-app
    spec:
      containers:
      - name: ovs
        image: jaibw/diagnostic-center:2
        env:
        - name: DBNAME
          value: postgres
        - name: DBUSER
          value: postgres
        - name: DBHOST
          value: postgres-svc
        - name: DBPORT
          value: "5432"
        - name: DBPASS
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: password
        ports:
        - containerPort: 8093
