apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
spec:
  selector:
    matchLabels:
      app: postgres-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
      - image: postgres:latest
        name: database
        env: 
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: password
        ports:
        - containerPort: 5432
          name: postgres
